"""Add IP logging and parental consent fields, UserLoginLog table

Revision ID: 305c208087c2
Revises: 2537e53bee69
Create Date: 2025-12-03 12:36:20.397463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305c208087c2'
down_revision = '2537e53bee69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_login_log', schema=None) as batch_op:
        batch_op.create_index('idx_login_log_action_type', ['action_type'], unique=False)
        batch_op.create_index('idx_login_log_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_login_log_ip', ['ip_address'], unique=False)
        batch_op.create_index('idx_login_log_user_action', ['user_id', 'action_type', 'action_date'], unique=False)
        batch_op.create_index('idx_login_log_user_date', ['user_id', 'action_date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('parental_consent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parental_consent_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('parental_consent_ip', sa.String(length=45), nullable=True))
        batch_op.create_index('idx_user_last_login_ip', ['last_login_ip'], unique=False)
        batch_op.create_index('idx_user_registration_ip', ['registration_ip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_registration_ip')
        batch_op.drop_index('idx_user_last_login_ip')
        batch_op.drop_column('parental_consent_ip')
        batch_op.drop_column('parental_consent_date')
        batch_op.drop_column('parental_consent')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('registration_ip')

    with op.batch_alter_table('user_login_log', schema=None) as batch_op:
        batch_op.drop_index('idx_login_log_user_date')
        batch_op.drop_index('idx_login_log_user_action')
        batch_op.drop_index('idx_login_log_ip')
        batch_op.drop_index('idx_login_log_created_at')
        batch_op.drop_index('idx_login_log_action_type')

    op.drop_table('user_login_log')
    # ### end Alembic commands ###
