"""Add UserConsent model for KVKK compliance

Revision ID: 4274ea6e10d5
Revises: 305c208087c2
Create Date: 2026-01-03 02:53:29.753240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4274ea6e10d5'
down_revision = '305c208087c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consent_text_hash', sa.String(length=64), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.create_index('idx_consent_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_consent_type', ['consent_type'], unique=False)
        batch_op.create_index('idx_consent_user_date', ['user_id', 'accepted_at'], unique=False)
        batch_op.create_index('idx_consent_user_type', ['user_id', 'consent_type'], unique=False)
        batch_op.create_index('idx_consent_withdrawn', ['withdrawn_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.drop_index('idx_consent_withdrawn')
        batch_op.drop_index('idx_consent_user_type')
        batch_op.drop_index('idx_consent_user_date')
        batch_op.drop_index('idx_consent_type')
        batch_op.drop_index('idx_consent_created_at')

    op.drop_table('user_consent')
    # ### end Alembic commands ###
