"""Initial migration

Revision ID: bdd29daa3640
Revises: 
Create Date: 2025-11-25 16:59:52.647619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd29daa3640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_slide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=True),
    sa.Column('button_url', sa.String(length=255), nullable=True),
    sa.Column('badge_text', sa.String(length=50), nullable=True),
    sa.Column('badge_color', sa.String(length=30), nullable=True),
    sa.Column('slide_type', sa.String(length=30), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.create_index('idx_province_code', ['code'], unique=False)
        batch_op.create_index('idx_province_name', ['name'], unique=False)

    op.create_table('school_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_type', schema=None) as batch_op:
        batch_op.create_index('idx_school_type_name', ['name'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sinif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sinif', sa.String(length=225), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sinif'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('sinif', schema=None) as batch_op:
        batch_op.create_index('idx_sinif_name', ['sinif'], unique=False)
        batch_op.create_index('idx_sinif_slug', ['slug'], unique=False)

    op.create_table('ders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ders_adi', sa.String(length=225), nullable=False),
    sa.Column('sinif_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['sinif_id'], ['sinif.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('ders', schema=None) as batch_op:
        batch_op.create_index('idx_ders_name', ['ders_adi'], unique=False)
        batch_op.create_index('idx_ders_sinif', ['sinif_id'], unique=False)
        batch_op.create_index('idx_ders_slug', ['slug'], unique=False)

    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.create_index('idx_district_name', ['name'], unique=False)
        batch_op.create_index('idx_district_province', ['province_id'], unique=False)

    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('school_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_type_id'], ['school_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index('idx_school_district_type', ['district_id', 'school_type_id'], unique=False)
        batch_op.create_index('idx_school_name', ['name'], unique=False)

    op.create_table('unite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unite', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ders_id'], ['ders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('unite', schema=None) as batch_op:
        batch_op.create_index('idx_unite_ders', ['ders_id'], unique=False)
        batch_op.create_index('idx_unite_name', ['unite'], unique=False)
        batch_op.create_index('idx_unite_slug', ['slug'], unique=False)

    op.create_table('icerik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=255), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unite_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['unite_id'], ['unite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('icerik', schema=None) as batch_op:
        batch_op.create_index('idx_icerik_created', ['created_at'], unique=False)
        batch_op.create_index('idx_icerik_slug', ['slug'], unique=False)
        batch_op.create_index('idx_icerik_title', ['baslik'], unique=False)
        batch_op.create_index('idx_icerik_unite', ['unite_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('class_no', sa.String(length=10), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('profile_completed_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_created_date', ['date_created'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_last_login', ['last_login'], unique=False)
        batch_op.create_index('idx_user_profile_completed', ['profile_completed'], unique=False)
        batch_op.create_index('idx_user_role', ['role'], unique=False)
        batch_op.create_index('idx_user_school_class', ['school_id', 'class_no'], unique=False)

    op.create_table('ders_notu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=False),
    sa.Column('baslik', sa.String(length=255), nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=True),
    sa.Column('sinif_id', sa.Integer(), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('unite_id', sa.Integer(), nullable=False),
    sa.Column('icerik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ders_id'], ['ders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['icerik_id'], ['icerik.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sinif_id'], ['sinif.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unite_id'], ['unite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ders_notu', schema=None) as batch_op:
        batch_op.create_index('idx_dersnotu_composite', ['sinif_id', 'ders_id', 'unite_id'], unique=False)
        batch_op.create_index('idx_dersnotu_icerik_date', ['icerik_id', 'eklenme_tarihi'], unique=False)
        batch_op.create_index('idx_dersnotu_title', ['baslik'], unique=False)

    op.create_table('soru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soru_resim', sa.String(length=255), nullable=False),
    sa.Column('cevap', sa.String(length=1), nullable=False),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('cozum_resim', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('unite_id', sa.Integer(), nullable=False),
    sa.Column('icerik_id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['icerik_id'], ['icerik.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unite_id'], ['unite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soru', schema=None) as batch_op:
        batch_op.create_index('idx_soru_created', ['created_at'], unique=False)
        batch_op.create_index('idx_soru_icerik', ['icerik_id'], unique=False)
        batch_op.create_index('idx_soru_unite', ['unite_id'], unique=False)
        batch_op.create_index('idx_soru_unite_icerik', ['unite_id', 'icerik_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_soru_reference_code'), ['reference_code'], unique=True)

    op.create_table('video_icerik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icerik_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('video_title', sa.String(length=255), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['icerik_id'], ['icerik.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_icerik', schema=None) as batch_op:
        batch_op.create_index('idx_video_aktif', ['aktif'], unique=False)
        batch_op.create_index('idx_video_created', ['eklenme_tarihi'], unique=False)
        batch_op.create_index('idx_video_icerik_sira', ['icerik_id', 'sira'], unique=False)

    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('icerik_id', sa.Integer(), nullable=True),
    sa.Column('soru_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('harcanan_sure', sa.Integer(), nullable=True),
    sa.Column('dogru_sayisi', sa.Integer(), nullable=True),
    sa.Column('yanlis_sayisi', sa.Integer(), nullable=True),
    sa.Column('bos_sayisi', sa.Integer(), nullable=True),
    sa.Column('puan', sa.Float(), nullable=True),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['icerik_id'], ['icerik.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soru_id'], ['soru.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index('idx_progress_composite', ['user_id', 'icerik_id', 'activity_type'], unique=False)
        batch_op.create_index('idx_progress_icerik', ['icerik_id'], unique=False)
        batch_op.create_index('idx_progress_points', ['user_id', 'puan'], unique=False)
        batch_op.create_index('idx_progress_soru', ['soru_id'], unique=False)
        batch_op.create_index('idx_progress_user_activity', ['user_id', 'activity_type'], unique=False)
        batch_op.create_index('idx_progress_user_date', ['user_id', 'tarih'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_progress_user_date')
        batch_op.drop_index('idx_progress_user_activity')
        batch_op.drop_index('idx_progress_soru')
        batch_op.drop_index('idx_progress_points')
        batch_op.drop_index('idx_progress_icerik')
        batch_op.drop_index('idx_progress_composite')

    op.drop_table('user_progress')
    with op.batch_alter_table('video_icerik', schema=None) as batch_op:
        batch_op.drop_index('idx_video_icerik_sira')
        batch_op.drop_index('idx_video_created')
        batch_op.drop_index('idx_video_aktif')

    op.drop_table('video_icerik')
    with op.batch_alter_table('soru', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soru_reference_code'))
        batch_op.drop_index('idx_soru_unite_icerik')
        batch_op.drop_index('idx_soru_unite')
        batch_op.drop_index('idx_soru_icerik')
        batch_op.drop_index('idx_soru_created')

    op.drop_table('soru')
    with op.batch_alter_table('ders_notu', schema=None) as batch_op:
        batch_op.drop_index('idx_dersnotu_title')
        batch_op.drop_index('idx_dersnotu_icerik_date')
        batch_op.drop_index('idx_dersnotu_composite')

    op.drop_table('ders_notu')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_school_class')
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_profile_completed')
        batch_op.drop_index('idx_user_last_login')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_created_date')

    op.drop_table('user')
    with op.batch_alter_table('icerik', schema=None) as batch_op:
        batch_op.drop_index('idx_icerik_unite')
        batch_op.drop_index('idx_icerik_title')
        batch_op.drop_index('idx_icerik_slug')
        batch_op.drop_index('idx_icerik_created')

    op.drop_table('icerik')
    with op.batch_alter_table('unite', schema=None) as batch_op:
        batch_op.drop_index('idx_unite_slug')
        batch_op.drop_index('idx_unite_name')
        batch_op.drop_index('idx_unite_ders')

    op.drop_table('unite')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index('idx_school_name')
        batch_op.drop_index('idx_school_district_type')

    op.drop_table('school')
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_index('idx_district_province')
        batch_op.drop_index('idx_district_name')

    op.drop_table('district')
    with op.batch_alter_table('ders', schema=None) as batch_op:
        batch_op.drop_index('idx_ders_slug')
        batch_op.drop_index('idx_ders_sinif')
        batch_op.drop_index('idx_ders_name')

    op.drop_table('ders')
    with op.batch_alter_table('sinif', schema=None) as batch_op:
        batch_op.drop_index('idx_sinif_slug')
        batch_op.drop_index('idx_sinif_name')

    op.drop_table('sinif')
    op.drop_table('settings')
    with op.batch_alter_table('school_type', schema=None) as batch_op:
        batch_op.drop_index('idx_school_type_name')

    op.drop_table('school_type')
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.drop_index('idx_province_name')
        batch_op.drop_index('idx_province_code')

    op.drop_table('province')
    op.drop_table('homepage_slide')
    # ### end Alembic commands ###
